pipeline {
  agent any
  tools{
    maven'maven3.9.8'
  }
  stages{
    stage("build"){
        steps{
            echo 'Compilingworkerapp'
            dir('worker'){
              sh 'mvn compile'
            }
        }
    }
    stage("test"){
        steps{
            echo 'Running Unit Tests on worker app'
        }
    }
    stage("package"){
        steps{
            echo 'Packaging worker app'
        }
    }
  }
  post{
    always{
        echo'Buildingmultibranchpipelineforworkeriscompleted..'
        }
    }
}

